// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7FPfUo9SOS9nW7Ph7RWFjfg9iGzaWSmQ',
    appId: '1:357698710928:web:6223e5498c0905b93c1715',
    messagingSenderId: '357698710928',
    projectId: 'nesne28-5e6f0',
    authDomain: 'nesne28-5e6f0.firebaseapp.com',
    storageBucket: 'nesne28-5e6f0.firebasestorage.app',
    measurementId: 'G-M828YYLB5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArmExoQChC8sKT6XayIqg_15mpFhHr56k',
    appId: '1:357698710928:android:0cc17e6857ee89453c1715',
    messagingSenderId: '357698710928',
    projectId: 'nesne28-5e6f0',
    storageBucket: 'nesne28-5e6f0.firebasestorage.app',
  );
}
